### ISSUE TITLE
Upon first use, got this issue

### ISSUE THREAD

**Issue by aubreypwd** [aubreypwd/wp-plugin-boilerplate#1]
```
[14-Oct-2017 19:23:43 UTC] PHP Fatal error:  Uncaught Error: Class 'aubreypwd\CampDavid\Shared' not found in /app/public/wp-content/plugins/camp-david/includes/class-app.php:132
Stack trace:
#0 /app/public/wp-content/plugins/camp-david/includes/class-app.php(76): aubreypwd\CampDavid\App->attach()
#1 /app/public/wp-content/plugins/camp-david/camp-david.php(42): aubreypwd\CampDavid\App->__construct('/app/public/wp-...')
#2 /app/public/wp-content/plugins/camp-david/camp-david.php(59): aubreypwd\CampDavid\app()
#3 /app/public/wp-admin/includes/plugin.php(560): include_once('/app/public/wp-...')
#4 /app/public/wp-admin/plugins.php(42): activate_plugin('camp-david/camp...', 'http://campdavi...', false)
#5 {main}
  thrown in /app/public/wp-content/plugins/camp-david/includes/class-app.php on line 132
[14-Oct-2017 19:23:43 UTC] PHP Fatal error:  Uncaught Error: Class 'aubreypwd\CampDavid\Shared' not found in /app/public/wp-content/plugins/camp-david/includes/class-app.php:132
Stack trace:
#0 /app/public/wp-content/plugins/camp-david/includes/class-app.php(76): aubreypwd\CampDavid\App->attach()
#1 /app/public/wp-content/plugins/camp-david/camp-david.php(42): aubreypwd\CampDavid\App->__construct('/app/public/wp-...')
#2 /app/public/wp-content/plugins/camp-david/camp-david.php(59): aubreypwd\CampDavid\app()
#3 /app/public/wp-admin/includes/plugin.php(1882): include('/app/public/wp-...')
#4 /app/public/wp-admin/plugins.php(164): plugin_sandbox_scrape('camp-david/camp...')
#5 {main}
  thrown in /app/public/wp-content/plugins/camp-david/includes/class-app.php on line 132
[14-Oct-2017 19:23:43 UTC] PHP Fatal error:  Uncaught Error: Class 'aubreypwd\CampDavid\Shared' not found in /app/public/wp-content/plugins/camp-david/includes/class-app.php:132
Stack trace:
#0 /app/public/wp-content/plugins/camp-david/includes/class-app.php(76): aubreypwd\CampDavid\App->attach()
#1 /app/public/wp-content/plugins/camp-david/camp-david.php(42): aubreypwd\CampDavid\App->__construct('/app/public/wp-...')
#2 /app/public/wp-content/plugins/camp-david/camp-david.php(59): aubreypwd\CampDavid\app()
#3 /app/public/wp-admin/includes/plugin.php(1882): include('/app/public/wp-...')
#4 /app/public/wp-admin/plugins.php(164): plugin_sandbox_scrape('camp-david/camp...')
#5 {main}
  thrown in /app/public/wp-content/plugins/camp-david/includes/class-app.php on line 132
```

**Comment by aubreypwd** [comment]
This was because I hadn't changed:

```
if ( 0 !== strpos( $class_name, 'Company\\Package\\' ) ) {
```

Once I changed that it worked :D
